PythonWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # Tạo đường dẫn liên kết với các app
    path('', include('sanpham.urls')),
    path('user/', include('user.urls')),
    path('gio-hang/', include('giohang.urls')),
    path('tim-kiem/', include('timkiem.urls')),
    path('phongthuy/', include('phongthuy.urls')),
    url(r'^admin/', include('dbbackup_ui.urls')),
    path('tin-tuc/', include('news.urls')),
    path('dau-gia/', include('DauGia.urls')),
    path('quantri/', include('quantri.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'tintuc'
urlpatterns = [
    path('', views.home, name='news'),
    path("danh-muc/<str:DuongDan>/", views.danhmuctintuc, name='danhmuctintuc'),
    path("<str:DuongDan>/", views.tintuc, name='tintuc'),
]

quantri/urls.py
from django.urls import path, re_path

from quantri.views.daugia import *
from quantri.views.donhang import *
from quantri.views.loaisim import *
from quantri.views.main import *
from quantri.views.mang import *
from quantri.views.sanpham import *
from quantri.views.cauhinh import *
from quantri.views.tintuc import *

app_name = 'quantri'

urlpatterns = [
    path('', main, name='main'),
    path('error', Quyen404, name='Quyen-truy-cap'),

    # san pham
    path('sanpham/them',ThemSanPham.as_view(),name='Them-san-pham'),
    path('sanpham/sua/<id>',SuaSanPham,name='Sua-san-pham'),
    path('sanpham/danh-sach',DanhSachSanPham.as_view(),name='Danh-sach-san-pham'),
    path('sanpham/xoa/<id>',XoaSanPham.as_view(),name='xoa-san-pham'),

    # nha mang
    path('mang/them/',ThemMang.as_view(),name='Them-mang'),
    path('mang/them/<id>',Suamang,name='Sua-mang'),
    path('mang/xoa/<id>',XoaMang.as_view(),name='xoa-mang'),

    # loai sim
    path('loai/them/',ThemLoaiSim.as_view(),name='Them-loai'),
    path('loai/them/<id>',Sualoaisim,name='Sua-loai'),
    path('loai/xoa/<id>',Xoaloaisim.as_view(),name='xoa-loai'),

    #cau hinh
    path('cau-hinh/cau-hinh-trang/',SuaCauHinhTrang,name='cau-hinh-trang'),
    path('cau-hinh/cau-hinh-seo/',SuaCauHinhSEO,name='cau-hinh-seo'),

    #tin tuc
    path('tin-tuc/danh-muc/',DanhSachLoaiTinTuc.as_view(),name='danh-sach-loai-tin-tuc'),
    path('tin-tuc/danh-muc/them-moi/',ThemLoaiTinTuc.as_view(),name='them-loai-tin-tuc'),
    path('tin-tuc/danh-muc/sua/<id>',SuaLoaiTinTuc,name='sua-loai-tin-tuc'),
    path('tin-tuc/danh-muc/xoa/<id>',XoaDanhMucTinTuc.as_view(),name='xoa-loai-tin-tuc'),

    path('tin-tuc/danh-sach-tin-tuc/',DanhSachTinTuc.as_view(),name='danh-sach-tin-tuc'),
    path('tin-tuc/danh-sach-tin-tuc/them-moi/',ThemTinTuc.as_view(),name='them-tin-tuc'),
    path('tin-tuc/danh-sach-tin-tuc/sua/<id>',SuaTinTuc,name='sua-tin-tuc'),
    path('tin-tuc/danh-sach-tin-tuc/xoa/<id>',XoaTinTuc.as_view(),name='xoa-tin-tuc'),

    #don hang
    path('donhang',DanhSachDonHang.as_view(),name='danh-sach-don-hang'),
    path('donhang/<id>',UpdateDonHang,name='cap-nhat-don-hang'),
    path('donhang/xoa/<id>',XoaDonHang.as_view(),name='xoa-don-hang'),

    # dau gia
    path('daugia',DanhSachDauGia.as_view(),name='danh-sach-dau-gia'),
    path('daugia/them/',Themdaugia.as_view(),name='them-dau-gia'),
    path('daugia/sua/<id>',Suadaugia,name='sua-dau-gia'),
    path('daugia/xoa/<id>',Xoadaugia.as_view(),name='xoa-dau-gia'),
]

sanpham/urls.py
from django.urls import path

from . import views

app_name = 'sanpham'
urlpatterns = [
    path('', views.index, name='home'),
    path("san-pham/<str:slug>", views.sanpham, name='sanpham'),
    path('sim-theo-gia/<str:slug>', views.simtheogia, name='simtheogia'),
    path('sim-theo-mang/<str:slug>', views.simtheomang, name='simtheomang'),
    path('sim-theo-loai/<str:slug>', views.simtheoloai, name='simtheoloai'),
    path('sim-nam-sinh/<str:slug>', views.simnamsinh, name='simnamsinh'),


]

user/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from sanpham.models import SimTheoLoai, SimNamSinh, NhaMang, SimTheoGia
from news.models import TinTuc, DanhMucTinTuc
import operator


app_name = 'user'
urlpatterns = [
    path("dang-ky/", views.dangky, name='dangky'),
    path("dang-nhap/", auth_views.LoginView.as_view(template_name='simso/page-user/dangnhap.html',
                                                    extra_context={
                                                        "stl": SimTheoLoai.objects.all(),
                                                        "sns": SimNamSinh.objects.all(),
                                                        "nm": NhaMang.objects.all(),
                                                        # "stg": sorted(SimTheoGia.objects.all(), key=operator.attrgetter('title')),
                                                        "dmtt1": DanhMucTinTuc.objects.filter(TieuDe='Bạn cần biết'),
                                                        "bcbs": DanhMucTinTuc.objects.filter(TieuDe='Bạn cần biết').order_by('-NgayTao')[0:5],
                                                        "dmtt2": DanhMucTinTuc.objects.filter(TieuDe='Tin mới cập nhật'),
                                                        "tmcns": DanhMucTinTuc.objects.filter(TieuDe='Tin mới cập nhật').order_by('-NgayTao')[0:5],
                                                    }),
         name='dangnhap'),
    path("dang-xuat/", auth_views.LogoutView.as_view(next_page='/'), name='dangxuat'),
    path("thong-tin-tai-khoan/", views.thongtintaikhoan, name='thongtintaikhoan'),
    path("doi-mat-khau/", views.doimatkhau, name='doimatkhau'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path("xac-thuc/", views.verify, name='xacthuc'),
    path("xac-thuc-sdt/", views.checkcode, name='xacthucsdt'),

]

quantri/views/sanpham.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, DeleteView

from quantri.froms.sanpham import ThemSanPhamForm
from sanpham.models import SanPham


@login_required(login_url='/user/dang-nhap')
def Quyen404(request):
    data = {"item": {'title': 'Lỗi truy cập'}}
    return render(request, 'quanly/page/404-user.html', data)


class ThemSanPham(SuccessMessageMixin,CreateView):
    model = SanPham
    form_class = ThemSanPhamForm
    template_name = 'quanly/page/them-san-pham.html'
    success_url = reverse_lazy('quantri:Them-san-pham')
    success_message = "Thêm sim thành công!"
    extra_context = {
        'class_tp': 'active',
        'item': 'Thêm sản phẩm mới'
    }
# Kiem tra quyen truy cap - Bao nhi
    @method_decorator(login_required(login_url=reverse_lazy('user:dangnhap')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('user:dangnhap')
        if self.request.user.is_authenticated and not self.request.user.is_superuser:
            return redirect('quantri:Quyen-truy-cap')
        return super().dispatch(self.request, *args, **kwargs)


@login_required
def SuaSanPham(request, id):
    obj = get_object_or_404(SanPham, id=id)
    form = ThemSanPhamForm(request.POST or None, instance=obj)
    context = {'form': form}

    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()
        messages.success(request, "Cập nhật thông tin sim thành công")
        context = {'form': form}
        return render(request, 'quanly/page/them-san-pham.html', context)

    else:
        context = {'form': form,
                   'error': 'Có gì đó sai sai'}
        return render(request, 'quanly/page/them-san-pham.html', context)

class DanhSachSanPham(ListView):
    model = SanPham
    paginate_by = 200  # if pagination is desired
    template_name = 'quanly/page/danh-sach-san-pham.html'
    queryset = SanPham.objects.filter(DaBan=False)
    context_object_name = 'sanpham'
    extra_context = {
        'title': 'Danh sách sim',
        'item' : 'Danh sách sim'
    }
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['sp_daban'] = SanPham.objects.filter(DaBan=True)
        return data

class XoaSanPham(SuccessMessageMixin,DeleteView):
    template_name = 'quanly/page/xoa-post.html'
    success_message = "Xoá thành công!"
    success_url = reverse_lazy('quantri:Danh-sach-san-pham')
    extra_context = {
        'title': 'Xoá sim',
        'item': 'Xoá sim'
    }

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(SanPham, id=id_)

sanpham/views.py
from django.db.models.aggregates import Max
from django.shortcuts import render, redirect
from .models import SanPham, SimTheoLoai, SimNamSinh, NhaMang, SimTheoGia
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from hoadon.models import HoaDon
from itertools import chain
from django.db.models import Q

# Create your views here.
def index(request):
    # Lấy dữ liệu từ database
    km = SanPham.objects.filter(TacVu='khuyenmai', DaBan=False)[0:12]
    vip = SanPham.objects.filter(TacVu='vip', DaBan=False)[0:9]
    vipdn = SanPham.objects.filter(TacVu='vipdn', DaBan=False)[0:9]
    thuong = SanPham.objects.filter(TacVu='thuong', DaBan=False)[0:999]

    stl = SimTheoLoai.objects.all()
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()
    hd = HoaDon.objects.order_by('-NgayDatHang')[0:5]


    Data = {
            "hd": hd,
            "km": km,
            "vip": vip,
            "vipdn": vipdn,
            "thuong": thuong,
            "stl": stl,
            "sns": sns,
            "nm": nm,
            "stg": stg,
            }
    return render(request, "simso/index.html", Data)

def sanpham(request, slug):
    # Lấy dữ liệu từ database
    try:
        sanpham = SanPham.objects.get(slug=slug, DaBan=False)
    except SanPham.DoesNotExist:
        return redirect('sanpham:home')

    sim1 = SanPham.objects.filter(Mang=sanpham.Mang).exclude(id=sanpham.id).order_by('-luotxem')[0:5]
    sim2 = SanPham.objects.filter(NamSinh=sanpham.NamSinh).exclude(id=sanpham.id).exclude(id__in=[i.id for i in sim1]).order_by('-luotxem')[0:5]
    sim3 = SanPham.objects.filter(LoaiGia=sanpham.LoaiGia).exclude(id=sanpham.id).exclude(id__in=[i.id for i in sim1]).exclude(id__in=[i.id for i in sim2]).order_by('-luotxem')[0:5]
    result_list = sorted(chain(sim1, sim2, sim3), key=lambda instance: instance.luotxem, reverse=True)[0:5]
   
    sanpham.luotxem += 1
    sanpham.save()

    stl = SimTheoLoai.objects.all()
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()
    hd = HoaDon.objects.order_by('-NgayDatHang')[0:5]

    Data = {'sanpham': sanpham,
            "hd": hd,
            "sim": result_list,
            "stl": stl,
            "stg": stg,
            "sns": sns,
            "nm": nm,
            }
    return render(request, 'simso/detail-sim/detail-sim.html', Data)

def error(request):
    return render(request, 'simso/page-user/error.html')


def simtheogia(request, slug):
    stg1 = SimTheoGia.objects.get(slug=slug)
    sanpham = stg1.sanpham_set.filter(DaBan=False)
    paginator = Paginator(sanpham, 25)  # Show 25 contacts per page
    page = request.GET.get('page')
    sanphams = paginator.get_page(page)

    stl = SimTheoLoai.objects.order_by('?')
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()
    hd = HoaDon.objects.order_by('-NgayDatHang')[0:5]

    Data = {
            'stg1': stg1,
            'sanpham': sanphams,
            "hd": hd,
            "stl": stl,
            "sns": sns,
            "stg": stg,
            "nm": nm,
            }
    return render(request, 'simso/category/sim-theo-gia.html', Data)


def simtheomang(request, slug):

    nm1 = NhaMang.objects.get(slug=slug)
    sanpham = nm1.sanpham_set.filter(DaBan=False)

    paginator = Paginator(sanpham, 70)  # Show 25 contacts per page

    page = request.GET.get('page')
    sanphams = paginator.get_page(page)
    stl = SimTheoLoai.objects.order_by('?')
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()
    hd = HoaDon.objects.order_by('-NgayDatHang')[0:5]
    Data = {
            'nm1': nm1,
            'sanpham': sanphams,
            "hd": hd,
            "stl": stl,
            "sns": sns,
            "nm": nm,
            "stg": stg,
            }
    return render(request, 'category/sim-theo-mang.html', Data)

def simtheoloai(request, slug):
    stl1 = SimTheoLoai.objects.get(slug=slug)

    sanpham = stl1.sanpham_set.filter(DaBan=False)
    paginator = Paginator(sanpham, 10)  # Show 25 contacts per page

    page = request.GET.get('page')
    sanphams = paginator.get_page(page)

    stl = SimTheoLoai.objects.order_by('?')
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()
    hd = HoaDon.objects.order_by('-NgayDatHang')[0:5]

    Data = {
            'stl1': stl1,
            'sanpham': sanphams,
            "hd": hd,
            "stl": stl,
            "sns": sns,
            "nm": nm,
            "stg": stg,

            }
    return render(request, 'category/sim-theo-loai.html', Data)


def simnamsinh(request, slug):
    sns1 = SimNamSinh.objects.get(slug=slug)
    sanpham = sns1.sanpham_set.filter(DaBan=False)
    # paginator = Paginator(sanpham, 10)  # Show 25 contacts per page
    # page = request.GET.get('page')
    # sanphams = paginator.get_page(page)

    stl = SimTheoLoai.objects.order_by('?')
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()
    hd = HoaDon.objects.order_by('-NgayDatHang')[0:5]


    Data = {
            'sns1': sns1,
            'sanpham': sanpham,
            "hd": hd,
            "stl": stl,
            "sns": sns,
            "nm": nm,
            "stg": stg,
            }
    return render(request, 'simso/category/sim-nam-sinh.html', Data)


def tknc(request, slug):
    sp = SanPham.objects.get(slug=slug, DaBan=False)
    Data = {
            'sp':sp,
            }
    return render(request, 'includes/timkiem/timkiem-nangcao.html', Data)

sanpham/templates/quanly/inc/menu-mobile.html
<div class="mobile-menu md:hidden">
            <div class="mobile-menu-bar">
                <a href="#" class="flex mr-auto">
                    <img alt="Midone Tailwind HTML Admin Template" class="w-6" src="/static/logo.svg">
                </a>
                <a href="javascript:" id="mobile-menu-toggler">
                    <i data-feather="bar-chart-2" class="w-8 h-8 text-white transform -rotate-90"></i> </a>
            </div>
            <ul class="border-t border-theme-24 py-5 hidden">
                    <li>
                        <a href="{% url 'quantri:main' %}" class="menu menu--{{ class.main }}">
                            <div class="menu__icon"> <i data-feather="home"></i> </div>
                            <div class="menu__title"> Bảng điều khiển </div>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'quantri:danh-sach-don-hang' %}" class="menu menu--{{ class.main }}">
                            <div class="menu__icon"> <i data-feather="credit-card"></i> </div>
                            <div class="menu__title"> Đơn hàng</div>
                        </a>
                    </li>

                     {% if request.user.is_superuser %}
                        <!---Kiem tra quyen truy cap-->
                    <li>
                        <a href="javascript:" class="menu">
                            <div class="menu__icon"> <i data-feather="file-plus"></i> </div>
                            <div class="menu__title">Quản lý sim <i data-feather="chevron-down" class="menu__sub-icon"></i> </div>
                        </a>
                        <ul class="">
                            <li>
                                <a href="{% url 'quantri:Them-san-pham' %}" class="menu menu--{{ class_tp }}">
                                    <div class="menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="menu__title">Thêm sim mới</div>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'quantri:Danh-sach-san-pham' %}" class="menu menu--{{ class_ds }}">
                                    <div class="menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="menu__title">Danh sách sim </div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:" class="menu">
                            <div class="menu__icon"> <i data-feather="credit-card"></i> </div>
                            <div class="menu__title">Quản lý tin tức <i data-feather="chevron-down" class="menu__sub-icon"></i> </div>
                        </a>
                        <ul class="">
                            <li>
                                <a href="{% url 'quantri:danh-sach-loai-tin-tuc' %}" class="menu menu--{{ class_tp }}">
                                    <div class="menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="menu__title">Danh mục tin tức</div>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'quantri:danh-sach-tin-tuc' %}" class="menu menu--{{ class_ds }}">
                                    <div class="menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="menu__title">Tin tức</div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    {% else %}

                    {% endif %}

                <!--------hoa don-------->
                    {% if request.user.is_superuser %}
                        <!---Kiem tra quyen truy cap-->
                    <li>
                        <a href="javascript:" class="menu">
                            <div class="menu__icon"> <i data-feather="file-text"></i> </div>
                            <div class="menu__title"> Quản lý danh mục <i data-feather="chevron-down" class="menu__sub-icon"></i> </div>
                        </a>
                        <ul class="">
                            <li>
                                <a href="{% url 'quantri:Them-mang' %}" class="menu menu--{{ class_tp }}">
                                    <div class="menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="menu__title">  Danh sách nhà mạng</div>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'quantri:Them-loai' %}" class="menu menu--{{ class_ds }}">
                                    <div class="menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="menu__title"> Danh mục loại sim </div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    {% else %}

                    {% endif %}
                <!----------->
                    <li class="side-nav__devider my-6"></li>
                    <li>
                        <a href="javascript:" class="menu menu--{{ class.profile }}">
                            <div class="menu__icon"> <i data-feather="trello"></i> </div>
                            <div class="menu__title">Tài khoản <i data-feather="chevron-down" class="menu__sub-icon"></i> </div>
                        </a>
                        <ul class="">
                            <li>
                                <a href="/" class="menu menu--{{ class.profile }}">
                                    <div class="menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="menu__title"> Thông tin cá nhân </div>
                                </a>
                            </li>
                            <li>
                                <a href="/" class="menu">
                                    <div class="menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="menu__title"> Đổi mật khẩu </div>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="side-nav__devider my-6"></li>

                    {% if request.user.is_superuser %}
                        <!---Kiem tra quyen truy cap-->
                    <li>
                        <a href="javascript:" class="menu">
                            <div class="menu__icon"> <i data-feather="inbox"></i> </div>
                            <div class="menu__title"> Cấu hình <i data-feather="chevron-down" class="menu__sub-icon"></i> </div>
                        </a>
                        <ul class="">
                            <li>
                                <a href="{%  url 'quantri:cau-hinh-trang' %}" class="menu menu--{{ class_tp }}">
                                    <div class="menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="menu__title"> Cấu hình trang </div>
                                </a>
                            </li>
                            <li>
                                <a href="{%  url 'quantri:cau-hinh-seo' %}" class="menu menu--{{ class_ds }}">
                                    <div class="menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="menu__title"> Cấu hình SEO </div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    {% else %}
                    {% endif %}

                </ul>
        </div>

sanpham/templates/quanly/inc/menu-pc.html
{% load static %}
<nav class="side-nav">
                <a href="#" class="intro-x flex items-center pl-5 pt-4">
                    <img alt="website quản lý căn hộ" class="w-6" src="/static/logo.svg">
                    <span class="hidden xl:block text-white text-lg ml-3"> WEB<span class="font-medium"> SIM SỐ</span> </span>
                </a>
                <div class="side-nav__devider my-6"></div>
        <ul>
                    <li>
                        <a href="{% url 'quantri:main' %}" class="side-menu side-menu--active">
                            <div class="side-menu__icon"> <i data-feather="home"></i> </div>
                            <div class="side-menu__title"> Bảng điều khiển </div>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;" class="side-menu">
                            <div class="side-menu__icon"> <i data-feather="box"></i> </div>
                            <div class="side-menu__title"> Quản lý sim <i data-feather="chevron-down" class="side-menu__sub-icon"></i> </div>
                        </a>
                        <ul class="">
                            <li>
                                <a href="{%  url 'quantri:Them-san-pham' %}" class="side-menu">
                                    <div class="side-menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="side-menu__title"> Thêm sim mới </div>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'quantri:Danh-sach-san-pham' %}" class="side-menu">
                                    <div class="side-menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="side-menu__title"> Danh sách sim </div>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'quantri:Them-mang' %}" class="side-menu">
                                    <div class="side-menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="side-menu__title"> Danh sách nhà mạng </div>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'quantri:Them-loai' %}" class="side-menu">
                                    <div class="side-menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="side-menu__title"> Danh mục loại sim </div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="side-menu">
                            <div class="side-menu__icon"> <i data-feather="inbox"></i> </div>
                            <div class="side-menu__title"> Cấu hình <i data-feather="chevron-down" class="side-menu__sub-icon"></i></div>
                        </a>
                        <ul class="">
                            <li>
                                <a href="{%  url 'quantri:cau-hinh-trang' %}" class="side-menu">
                                    <div class="side-menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="side-menu__title"> Cấu hình trang </div>
                                </a>
                            </li>
                            <li>
                                <a href="{%  url 'quantri:cau-hinh-seo' %}" class="side-menu">
                                    <div class="side-menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="side-menu__title"> Cấu hình SEO </div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'quantri:danh-sach-don-hang' %}" class="side-menu">
                            <div class="side-menu__icon"> <i data-feather="hard-drive"></i> </div>
                            <div class="side-menu__title"> Đơn hàng </div>
                        </a>
                    </li>
                    <li>
                        <a class="side-menu">
                            <div class="side-menu__icon"> <i data-feather="credit-card"></i> </div>
                            <div class="side-menu__title"> Tin tức <i data-feather="chevron-down" class="side-menu__sub-icon"></i></div>
                        </a>
                        <ul class="">
                            <li>
                                <a href="{% url 'quantri:danh-sach-loai-tin-tuc' %}" class="side-menu">
                                    <div class="side-menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="side-menu__title"> Danh sách loại tin tức </div>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'quantri:danh-sach-tin-tuc' %}" class="side-menu">
                                    <div class="side-menu__icon"> <i data-feather="activity"></i> </div>
                                    <div class="side-menu__title"> Danh sách tin tức </div>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'quantri:danh-sach-dau-gia' %}" class="side-menu">
                            <div class="side-menu__icon"> <i data-feather="message-square"></i> </div>
                            <div class="side-menu__title"> Đấu giá </div>
                        </a>
                    </li>

                    <li class="side-nav__devider my-6"></li>
                </ul>

</nav>