PythonWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # Tạo đường dẫn liên kết với các app
    path('', include('sanpham.urls')),
    path('user/', include('user.urls')),
    path('gio-hang/', include('giohang.urls')),
    path('tim-kiem/', include('timkiem.urls')),
    path('phongthuy/', include('phongthuy.urls')),
    url(r'^admin/', include('dbbackup_ui.urls')),
    path('tin-tuc/', include('news.urls')),
    path('dau-gia/', include('DauGia.urls')),
    path('quantri/', include('quantri.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'tintuc'
urlpatterns = [
    path('', views.home, name='news'),
    path("danh-muc/<str:DuongDan>/", views.danhmuctintuc, name='danhmuctintuc'),
    path("<str:DuongDan>/", views.tintuc, name='tintuc'),
]

quantri/urls.py
from django.urls import path, re_path

from quantri.views.daugia import *
from quantri.views.donhang import *
from quantri.views.loaisim import *
from quantri.views.main import *
from quantri.views.mang import *
from quantri.views.sanpham import *
from quantri.views.cauhinh import *
from quantri.views.tintuc import *

app_name = 'quantri'

urlpatterns = [
    path('', main, name='main'),
    path('error', Quyen404, name='Quyen-truy-cap'),

    # san pham
    path('sanpham/them',ThemSanPham.as_view(),name='Them-san-pham'),
    path('sanpham/sua/<id>',SuaSanPham,name='Sua-san-pham'),
    path('sanpham/danh-sach',DanhSachSanPham.as_view(),name='Danh-sach-san-pham'),
    path('sanpham/xoa/<id>',XoaSanPham.as_view(),name='xoa-san-pham'),

    # nha mang
    path('mang/them/',ThemMang.as_view(),name='Them-mang'),
    path('mang/them/<id>',Suamang,name='Sua-mang'),
    path('mang/xoa/<id>',XoaMang.as_view(),name='xoa-mang'),

    # loai sim
    path('loai/them/',ThemLoaiSim.as_view(),name='Them-loai'),
    path('loai/them/<id>',Sualoaisim,name='Sua-loai'),
    path('loai/xoa/<id>',Xoaloaisim.as_view(),name='xoa-loai'),

    #cau hinh
    path('cau-hinh/cau-hinh-trang/',SuaCauHinhTrang,name='cau-hinh-trang'),
    path('cau-hinh/cau-hinh-seo/',SuaCauHinhSEO,name='cau-hinh-seo'),

    #tin tuc
    path('tin-tuc/danh-muc/',DanhSachLoaiTinTuc.as_view(),name='danh-sach-loai-tin-tuc'),
    path('tin-tuc/danh-muc/them-moi/',ThemLoaiTinTuc.as_view(),name='them-loai-tin-tuc'),
    path('tin-tuc/danh-muc/sua/<id>',SuaLoaiTinTuc,name='sua-loai-tin-tuc'),
    path('tin-tuc/danh-muc/xoa/<id>',XoaDanhMucTinTuc.as_view(),name='xoa-loai-tin-tuc'),

    path('tin-tuc/danh-sach-tin-tuc/',DanhSachTinTuc.as_view(),name='danh-sach-tin-tuc'),
    path('tin-tuc/danh-sach-tin-tuc/them-moi/',ThemTinTuc.as_view(),name='them-tin-tuc'),
    path('tin-tuc/danh-sach-tin-tuc/sua/<id>',SuaTinTuc,name='sua-tin-tuc'),
    path('tin-tuc/danh-sach-tin-tuc/xoa/<id>',XoaTinTuc.as_view(),name='xoa-tin-tuc'),

    #don hang
    path('donhang',DanhSachDonHang.as_view(),name='danh-sach-don-hang'),
    path('donhang/<id>',UpdateDonHang,name='cap-nhat-don-hang'),
    path('donhang/xoa/<id>',XoaDonHang.as_view(),name='xoa-don-hang'),

    # dau gia
    path('daugia',DanhSachDauGia.as_view(),name='danh-sach-dau-gia'),
    path('daugia/them/',Themdaugia.as_view(),name='them-dau-gia'),
    path('daugia/sua/<id>',Suadaugia,name='sua-dau-gia'),
    path('daugia/xoa/<id>',Xoadaugia.as_view(),name='xoa-dau-gia'),
]

sanpham/urls.py
from django.urls import path

from . import views

app_name = 'sanpham'
urlpatterns = [
    path('', views.index, name='home'),
    path("san-pham/<str:slug>", views.sanpham, name='sanpham'),
    path('sim-theo-gia/<str:slug>', views.simtheogia, name='simtheogia'),
    path('sim-theo-mang/<str:slug>', views.simtheomang, name='simtheomang'),
    path('sim-theo-loai/<str:slug>', views.simtheoloai, name='simtheoloai'),
    path('sim-nam-sinh/<str:slug>', views.simnamsinh, name='simnamsinh'),


]

sanpham/models.py
from django.db import models
from django.template.defaultfilters import truncatechars
from PythonWeb.utils import get_unique_slug
import django_recommend
##
# Chọn sim vip _ thường
##

Default_img = '/default.png'

SIM_CHOICES = (
    ('khuyenmai', 'Khuyến Mãi'),
    ('thuong', 'Sim Thường'),
    ('vip', 'Sim Vip'),
    ('vipdn', 'Sim Vip Doanh Nhân'))

##
# Tạo danh muc san pham _Duc
##
class SimTheoGia(models.Model):
    title = models.CharField(max_length=100,verbose_name='Tiêu đề',unique=True)
    slug = models.SlugField(max_length=100, null=False, default='')

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Sim theo giá'


class NhaMang(models.Model):
    title = models.CharField(max_length=100,verbose_name='Tiêu đề',unique=True)
    slug = models.SlugField(max_length=100, null=False, default='')

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Nhà mạng'


class SimTheoLoai(models.Model):
    title = models.CharField(max_length=100,verbose_name='Tiêu đề')
    slug = models.SlugField(max_length=100, null=False, default='')

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Sim theo loại'


class SimNamSinh(models.Model):
    title = models.CharField(max_length=100,verbose_name='Tiêu đề')
    slug = models.SlugField(max_length=100, null=False, default='')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Sim năm sinh'


# Tạo bảng sản phẩm
class SanPham(models.Model):
    LoaiSims = models.ManyToManyField(SimTheoLoai,default=0, verbose_name='Loại sim')
    slug = models.SlugField(max_length=100, null=False, default='')
    luotxem = models.IntegerField(default=1)
    TacVu = models.CharField(max_length=100, choices=SIM_CHOICES,default='thuong',verbose_name='Tác vụ trang chủ')
    SoSim = models.CharField(max_length=100, verbose_name='Số sim',unique=True)
    Gia = models.IntegerField(verbose_name='Giá bán')
    Mang = models.ForeignKey(NhaMang, on_delete=models.CASCADE, null=True, verbose_name='Nhà Mạng')
    LoaiGia = models.ForeignKey(SimTheoGia, on_delete=models.CASCADE, null=True, verbose_name='Sim theo giá ')
    NamSinh = models.ForeignKey(SimNamSinh, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Theo năm sinh ')
    NgayNhap = models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập')
    DaBan = models.BooleanField(default=False, verbose_name='Đã bán')

    def __str__(self):
        return self.SoSim

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'SoSim', 'slug')
        super().save(*args, **kwargs)

    def get_loaisims(self):
        return " - ".join([s.title for s in self.LoaiSims.all()])

    def mark_viewed_by(self, user):

        """Record that the given Django user viewed this quote."""
        django_recommend.setdefault_score(user, self, 1)

    def mark_viewed_by_anonymous(self, session_key):
        """Record a non-authenticated user viewed this quote."""
        django_recommend.setdefault_score(session_key, self, 1)

    get_loaisims.short_description = "Loại sim"
    class Meta:
        verbose_name_plural = 'Sản Phẩm'

quantri/views/sanpham.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, DeleteView

from quantri.froms.sanpham import ThemSanPhamForm
from sanpham.models import SanPham


@login_required(login_url='/user/dang-nhap')
def Quyen404(request):
    data = {"item": {'title': 'Lỗi truy cập'}}
    return render(request, 'quanly/page/404-user.html', data)


class ThemSanPham(SuccessMessageMixin,CreateView):
    model = SanPham
    form_class = ThemSanPhamForm
    template_name = 'quanly/page/them-san-pham.html'
    success_url = reverse_lazy('quantri:Them-san-pham')
    success_message = "Thêm sim thành công!"
    extra_context = {
        'class_tp': 'active',
        'item': 'Thêm sản phẩm mới'
    }
# Kiem tra quyen truy cap - Bao nhi
    @method_decorator(login_required(login_url=reverse_lazy('user:dangnhap')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('user:dangnhap')
        if self.request.user.is_authenticated and not self.request.user.is_superuser:
            return redirect('quantri:Quyen-truy-cap')
        return super().dispatch(self.request, *args, **kwargs)


@login_required
def SuaSanPham(request, id):
    obj = get_object_or_404(SanPham, id=id)
    form = ThemSanPhamForm(request.POST or None, instance=obj)
    context = {'form': form}

    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()
        messages.success(request, "Cập nhật thông tin sim thành công")
        context = {'form': form}
        return render(request, 'quanly/page/them-san-pham.html', context)

    else:
        context = {'form': form,
                   'error': 'Có gì đó sai sai'}
        return render(request, 'quanly/page/them-san-pham.html', context)

class DanhSachSanPham(ListView):
    model = SanPham
    paginate_by = 200  # if pagination is desired
    template_name = 'quanly/page/danh-sach-san-pham.html'
    queryset = SanPham.objects.filter(DaBan=False)
    context_object_name = 'sanpham'
    extra_context = {
        'title': 'Danh sách sim',
        'item' : 'Danh sách sim'
    }
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['sp_daban'] = SanPham.objects.filter(DaBan=True)
        return data

class XoaSanPham(SuccessMessageMixin,DeleteView):
    template_name = 'quanly/page/xoa-post.html'
    success_message = "Xoá thành công!"
    success_url = reverse_lazy('quantri:Danh-sach-san-pham')
    extra_context = {
        'title': 'Xoá sim',
        'item': 'Xoá sim'
    }

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(SanPham, id=id_)

quantri/views/tintuc.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, DeleteView

from quantri.froms.tintuc import ThemTinTucForm, ThemLoaiTinTucForm
from news.models import TinTuc, DanhMucTinTuc


@login_required(login_url='/user/dang-nhap')
def Quyen404(request):
    data = {"item": {'title': 'Lỗi truy cập'}}
    return render(request, 'quanly/page/404-user.html', data)


class ThemLoaiTinTuc(SuccessMessageMixin,CreateView):
    model = DanhMucTinTuc
    form_class = ThemLoaiTinTucForm
    template_name = 'quanly/page/tintuc/them-loai-tin-tuc.html'
    success_url = reverse_lazy('quantri:danh-sach-loai-tin-tuc')
    success_message = "Thêm loại tin tức thành công!"
    extra_context = {
        'class_tp': 'active',
        'title': 'Thêm loại tin tức mới',
        'item': 'Thêm loại tin tức mới'
    }
# Kiem tra quyen truy cap - Bao nhi
    @method_decorator(login_required(login_url=reverse_lazy('user:dangnhap')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('user:dangnhap')
        if self.request.user.is_authenticated and not self.request.user.is_superuser:
            return redirect('quantri:Quyen-truy-cap')
        return super().dispatch(self.request, *args, **kwargs)


@login_required
def SuaLoaiTinTuc(request, id):
    obj = get_object_or_404(DanhMucTinTuc, id=id)
    form = ThemLoaiTinTucForm(request.POST or None, instance=obj)
    context = {'form': form,
                'title': 'Sửa loại tin tức',
                'item': 'Sửa loại tin tức'}

    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()
        messages.success(request, "Cập nhật thông tin danh mục tin tức thành công")
        context = {'form': form,
                    'title': 'Sửa loại tin tức',
                    'item': 'Sửa loại tin tức'}
        return render(request, 'quanly/page/tintuc/them-loai-tin-tuc.html', context)

    else:
        context = {'form': form,
                    'title': 'Sửa loại tin tức',
                    'item': 'Sửa loại tin tức',
                   'error': 'Có gì đó sai sai'}
        return render(request, 'quanly/page/tintuc/them-loai-tin-tuc.html', context)

class ThemTinTuc(SuccessMessageMixin,CreateView):
    model = TinTuc
    form_class = ThemTinTucForm
    template_name = 'quanly/page/tintuc/them-tin-tuc.html'
    success_url = reverse_lazy('quantri:danh-sach-tin-tuc')
    success_message = "Thêm tin tức thành công!"
    extra_context = {
        'class_tp': 'active',
        'title': 'Thêm tin tức mới',
        'item': 'Thêm tin tức mới'
    }
# Kiem tra quyen truy cap - duc
    @method_decorator(login_required(login_url=reverse_lazy('user:dangnhap')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('user:dangnhap')
        if self.request.user.is_authenticated and not self.request.user.is_superuser:
            return redirect('quantri:Quyen-truy-cap')
        return super().dispatch(self.request, *args, **kwargs)


@login_required
def SuaTinTuc(request, id):
    obj = get_object_or_404(TinTuc, id=id)
    form = ThemTinTucForm(request.POST or None, instance=obj)
    context = {'form': form,
                'title': 'Sửa tin tức',
                'item': 'Sửa tin tức'}

    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()
        messages.success(request, "Cập nhật thông tin tin tức thành công")
        context = {'form': form,
                    'title': 'Sửa tin tức',
                    'item': 'Sửa tin tức'}
        return render(request, 'quanly/page/tintuc/them-tin-tuc.html', context)

    else:
        context = {'form': form,
                    'title': 'Sửa loại tin tức',
                    'item': 'Sửa loại tin tức',
                   'error': 'Có gì đó sai sai'}
        return render(request, 'quanly/page/tintuc/them-tin-tuc.html', context)

class DanhSachTinTuc(ListView):
    model = TinTuc
    paginate_by = 20  # if pagination is desired
    template_name = 'quanly/page/tintuc/tin-tuc.html'
    queryset = TinTuc.objects.all()
    context_object_name = 'tintuc'
    extra_context = {
        'title': 'Danh sách tin tức',
        'item' : 'Danh sách tin tức'
    }
   

class DanhSachLoaiTinTuc(ListView):
    model = DanhMucTinTuc
    paginate_by = 20  # if pagination is desired
    template_name = 'quanly/page/tintuc/danh-muc-tin-tuc.html'
    queryset = DanhMucTinTuc.objects.all()
    context_object_name = 'danhmuctintuc'
    extra_context = {
        'title': 'Danh sách loại tin tức',
        'item' : 'Danh sách loại tin tức'
    }
    

class XoaDanhMucTinTuc(SuccessMessageMixin,DeleteView):
    template_name = 'quanly/page/xoa-post.html'
    success_message = "Xoá thành công!"
    success_url = reverse_lazy('quantri:danh-sach-loai-tin-tuc')
    extra_context = {
        'title': 'Xoá danh mục',
        'item': 'Xoá  danh mục'
    }

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(DanhMucTinTuc, id=id_)

class XoaTinTuc(SuccessMessageMixin,DeleteView):
    template_name = 'quanly/page/xoa-post.html'
    success_message = "Xoá thành công!"
    success_url = reverse_lazy('quantri:danh-sach-tin-tuc')
    extra_context = {
        'title': 'Xoá tin',
        'item': 'Xoá tin'
    }

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(TinTuc, id=id_)

sanpham/templates/quanly/page/tintuc/danh-muc-tin-tuc.html
{% extends 'quanly/main.html' %}
{% block main %}
    {% load humanize %}
<div class="content">
    {% include 'quanly/inc/topbar.html' %}
       <!-- END: Top Bar -->
                <div class="intro-y flex items-center mt-8">
                    <h2 class="text-lg font-medium mr-auto">
                       {{ title }}
                    </h2>
                </div>
    <div class="pos gap-5 mt-5">
    <!---Menu --->
    <!---end Menu --->
        <!-- Tat ca  -->
        <div class="tab-content">
            <div class="tab-content__pane active" id="all">
                <a href="{% url 'quantri:them-loai-tin-tuc' %}"><button class="button w-50 mr-1 mb-2 bg-theme-9 text-white">Thêm loại tin tức</button></a>
                        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
                                <table class="table table-report -mt-2">
                                    <thead>
                                        <tr>
                                            <th class="whitespace-no-wrap">Tiêu đề</th>
                                            <th class="whitespace-no-wrap">Đường dẫn</th>
                                            <th class="text-center whitespace-no-wrap">Tác vụ</th>
                                        </tr>
                                    </thead>
                                    {%  for d in danhmuctintuc %}
                                    <tbody>
                                        <tr class="intro-x">
                                            <td>
                                                <a href="#" target="_blank" class="font-medium whitespace-no-wrap">{{ d.TieuDe }}</a>
                                            </td>
                                            <td class="w-40">
                                                <p>{{ d.DuongDan }}</p>
                                            </td>
                                            <td class="table-report__action w-56">
                                                <div class="flex justify-center items-center">
                                                    <a class="flex items-center mr-3" href="{% url 'quantri:sua-loai-tin-tuc' d.id %}" target="_blank"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Sửa </a>
                                                    <a class="flex items-center text-theme-6" href="{% url 'quantri:xoa-loai-tin-tuc' d.id %}" target="_blank"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Xoá </a>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                    {% endfor %}
                                </table>
                            </div>
            </div>
            <!-- END: -->
    </div>
</div>
    <link rel="stylesheet" href="/static/css/nha-mang.css">
{% endblock %}

sanpham/templates/quanly/page/tintuc/them-loai-tin-tuc.html
{% extends 'quanly/main.html' %}

{% block main %}
<div class="content">
    {% include 'quanly/inc/topbar.html' %}
       <!-- END: Top Bar -->
                <div class="intro-y flex items-center mt-8">
                    <h2 class="text-lg font-medium mr-auto">
                       {{ title }}
                    </h2>
                </div>
    <form id="dang-bai" action="" method="post">
        {% csrf_token %}
        {{ form.errors }}
        <!-- BEGIN: Form Layout -->
        <div class="grid grid-cols-12 gap-6 mt-5" style="background: white">
            <div class="intro-y col-span-12 lg:col-span-12">
                <div class="intro-y box p-5">
                    <div class="mt-3">
                        <label>Nhập tiêu đề</label>
                        <div class="relative mx-auto">
                            {{ form.TieuDe }}
                            {{ form.TieuDe.errors }}
                        </div>
                    </div>
                    <div class="text-right mt-5">
                        <button type="submit" id="toast" class="button w-24 bg-theme-1 text-white">Lưu lại</button>
                    </div>
                </div>
            </div>
            
        </div>
        <!-- END: Form Layout -->
    </form>
</div>
{% endblock %}

sanpham/templates/quanly/page/tintuc/them-tin-tuc.html
{% extends 'quanly/main.html' %}

{% block main %}
<div class="content">
    {% include 'quanly/inc/topbar.html' %}
       <!-- END: Top Bar -->
                <div class="intro-y flex items-center mt-8">
                    <h2 class="text-lg font-medium mr-auto">
                       {{ title }}
                    </h2>
                </div>
    <form id="dang-bai" action="" method="post">
        {% csrf_token %}
        {{ form.errors }}
        <!-- BEGIN: Form Layout -->
        <div class="grid grid-cols-12 gap-6 mt-5" style="background: white">
            <div class="intro-y col-span-12 lg:col-span-12">
                <div class="intro-y box p-5">
                    <div class="mt-3">
                        <label>Chọn loại tin tức</label>
                        <div class="relative mx-auto">
                            {{ form.LoaiTinTuc }}
                            {{ form.LoaiTinTuc.errors }}
                        </div>
                    </div>
                    <div class="mt-3">
                        <label>Nhập tiêu đề</label>
                        <div class="relative mx-auto">
                            {{ form.TieuDe }}
                            {{ form.TieuDe.errors }}
                        </div>
                    </div>
                    <div class="mt-3">
                        <label>Nhập mô tả ngắn</label>
                        <div class="relative mx-auto">
                            {{ form.MoTaNgan }}
                            {{ form.MoTaNgan.errors }}
                        </div>
                    </div>
                    <div class="mt-3">
                        <label>Nhập nội dung</label>
                        <div class="relative mx-auto">
                            {{ form.NoiDung }}
                            {{ form.NoiDung.errors }}
                        </div>
                    </div>
                    <div class="text-right mt-5">
                        <button type="submit" id="toast" class="button w-24 bg-theme-1 text-white">Lưu lại</button>
                    </div>
                </div>
            </div>
            
        </div>
        <!-- END: Form Layout -->
    </form>
</div>
{% endblock %}

sanpham/templates/quanly/page/tintuc/tin-tuc.html
{% extends 'quanly/main.html' %}
{% block main %}
    {% load humanize %}
<div class="content">
    {% include 'quanly/inc/topbar.html' %}
       <!-- END: Top Bar -->
                <div class="intro-y flex items-center mt-8">
                    <h2 class="text-lg font-medium mr-auto">
                       {{ title }}
                    </h2>
                </div>
    <div class="pos gap-5 mt-5">
    <!---Menu --->
    <!---end Menu --->
        <!-- Tat ca  -->
        <div class="tab-content">
            <div class="tab-content__pane active" id="all">
                <a href="{% url 'quantri:them-tin-tuc' %}"><button class="button w-50 mr-1 mb-2 bg-theme-9 text-white">Thêm tin tức</button></a>
                        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
                                <table class="table table-report -mt-2">
                                    <thead>
                                        <tr>
                                            <th class="whitespace-no-wrap">Tiêu đề</th>
                                            <th class="whitespace-no-wrap">Mô tả ngắn</th>
                                            <th class="whitespace-no-wrap">Đường dẫn</th>
                                            <th class="whitespace-no-wrap">Loại tin tức</th>
                                            <th class="text-center whitespace-no-wrap">Tác vụ</th>
                                        </tr>
                                    </thead>
                                    {%  for d in tintuc %}
                                    <tbody>
                                        <tr class="intro-x">
                                            <td>
                                                <a href="{% url 'tintuc:tintuc' d.DuongDan %}" target="_blank" class="font-medium whitespace-no-wrap">{{ d.TieuDe }}</a>
                                                <div class="text-gray-600 text-xs whitespace-no-wrap"> Ngày nhập {{ d.NgayTao|date:'d/m/yy' }}</div>
                                            </td>
                                            <td class="w-40">
                                                <p>{{ d.MoTaNgan }}</p>
                                            </td>
                                            <td class="w-40">
                                                <p>{{ d.DuongDan }}</p>
                                            </td>
                                            <td class="w-40">
                                                <p>{{ d.LoaiTinTuc }}</p>
                                            </td>
                                            <td class="table-report__action w-56">
                                                <div class="flex justify-center items-center">
                                                    <a class="flex items-center mr-3" href="{% url 'quantri:sua-tin-tuc' d.id %}" target="_blank"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Sửa </a>
                                                    <a class="flex items-center text-theme-6" href="{% url 'quantri:xoa-tin-tuc' d.id %}" target="_blank"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Xoá </a>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                    {% endfor %}
                                </table>
                            </div>
            </div>
            <!-- END: -->
    </div>
</div>
    <link rel="stylesheet" href="/static/css/nha-mang.css">
{% endblock %}